version: "1.0"
info:
  model: int-scaffold
packages:
- name: EdgeICUI_AutomaionProject0915
  gitServerName: ICAccount0915
  gitUrl: https://github.com/MeghaRaj69/EdgeICUI_AutomaionProject0915
  gitUsername: MeghaRaj69
  gitToken: edge.scaffolding.EdgeICUI_AutomaionProject0915.ICAccount0915.gitToken
  gitBranch: main
